//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WYZTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WYZTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap About {
            get {
                object obj = ResourceManager.GetObject("About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accept {
            get {
                object obj = ResourceManager.GetObject("accept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addPattern {
            get {
                object obj = ResourceManager.GetObject("addPattern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alert {
            get {
                object obj = ResourceManager.GetObject("alert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error en la aplicación. Por favor, envíe el fichero {0} a:
        ///augusto.ruiz@gmail.com.
        ///¡Gracias!.
        /// </summary>
        internal static string ApplicationError {
            get {
                return ResourceManager.GetString("ApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivos WYZTracker .ARP (*.arp)|*.arp|Todos los Archivos (*.*)|*.*.
        /// </summary>
        internal static string ArpeggioFilter {
            get {
                return ResourceManager.GetString("ArpeggioFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tríadas Aumentadas.
        /// </summary>
        internal static string AugmentedTriad {
            get {
                return ResourceManager.GetString("AugmentedTriad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_cancel {
            get {
                object obj = ResourceManager.GetObject("button_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canal {0}.
        /// </summary>
        internal static string ChannelWithNumber {
            get {
                return ResourceManager.GetString("ChannelWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cromática.
        /// </summary>
        internal static string Chromatic {
            get {
                return ResourceManager.GetString("Chromatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clonePattern {
            get {
                object obj = ResourceManager.GetObject("clonePattern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amstrad CPC.
        /// </summary>
        internal static string CPC {
            get {
                return ResourceManager.GetString("CPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap de {
            get {
                object obj = ResourceManager.GetObject("de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tríadas Disminuidas.
        /// </summary>
        internal static string DiminishedTriad {
            get {
                return ResourceManager.GetString("DiminishedTriad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dórica.
        /// </summary>
        internal static string Dorian {
            get {
                return ResourceManager.GetString("Dorian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WYZTracker necesita OpenAL para funcionar correctamente. ¿Desea descargarlo ahora?.
        /// </summary>
        internal static string DownloadOpenAL {
            get {
                return ResourceManager.GetString("DownloadOpenAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_add {
            get {
                object obj = ResourceManager.GetObject("edit_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_remove {
            get {
                object obj = ResourceManager.GetObject("edit_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap el {
            get {
                object obj = ResourceManager.GetObject("el", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap en {
            get {
                object obj = ResourceManager.GetObject("en", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_0000 {
            get {
                object obj = ResourceManager.GetObject("env_0000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_0100 {
            get {
                object obj = ResourceManager.GetObject("env_0100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_1000 {
            get {
                object obj = ResourceManager.GetObject("env_1000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_1001 {
            get {
                object obj = ResourceManager.GetObject("env_1001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_1010 {
            get {
                object obj = ResourceManager.GetObject("env_1010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_1011 {
            get {
                object obj = ResourceManager.GetObject("env_1011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_1100 {
            get {
                object obj = ResourceManager.GetObject("env_1100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_1101 {
            get {
                object obj = ResourceManager.GetObject("env_1101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_1110 {
            get {
                object obj = ResourceManager.GetObject("env_1110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_1111 {
            get {
                object obj = ResourceManager.GetObject("env_1111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_continue {
            get {
                object obj = ResourceManager.GetObject("env_continue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_none {
            get {
                object obj = ResourceManager.GetObject("env_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap es {
            get {
                object obj = ResourceManager.GetObject("es", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exportarWYZ {
            get {
                object obj = ResourceManager.GetObject("exportarWYZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivos de audio .OGG (*.ogg)|*.ogg|Archivos de audio .WAV (*.wav)|*.wav|Todos los Archivos (*.*)|*.*.
        /// </summary>
        internal static string ExportFilter {
            get {
                return ResourceManager.GetString("ExportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filenew {
            get {
                object obj = ResourceManager.GetObject("filenew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileopen {
            get {
                object obj = ResourceManager.GetObject("fileopen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filesave {
            get {
                object obj = ResourceManager.GetObject("filesave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FX.
        /// </summary>
        internal static string FX {
            get {
                return ResourceManager.GetString("FX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivos de instrumentos WYZTracker .FX (*.fx)|*.fx|Archivos WYZTracker .WYZ (*.wyz)|*.wyz|Todos los Archivos (*.*)|*.*.
        /// </summary>
        internal static string FXFilter {
            get {
                return ResourceManager.GetString("FXFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Armónica menor.
        /// </summary>
        internal static string HarmonicMinor {
            get {
                return ResourceManager.GetString("HarmonicMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este identificador lo está usando el efecto &apos;{0}&apos;..
        /// </summary>
        internal static string IdAlreadyInUse {
            get {
                return ResourceManager.GetString("IdAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap importarMus {
            get {
                object obj = ResourceManager.GetObject("importarMus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivos de instrumentos WYZTracker .INS (*.ins)|*.ins|Archivos WYZTracker .WYZ (*.wyz)|*.wyz|Todos los Archivos (*.*)|*.*.
        /// </summary>
        internal static string INSFilter {
            get {
                return ResourceManager.GetString("INSFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este identificador lo está usando el instrumento &apos;{0}&apos;..
        /// </summary>
        internal static string InstrIdAlreadyInUse {
            get {
                return ResourceManager.GetString("InstrIdAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keyboard {
            get {
                object obj = ResourceManager.GetObject("keyboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lidia.
        /// </summary>
        internal static string Lydian {
            get {
                return ResourceManager.GetString("Lydian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor.
        /// </summary>
        internal static string Major {
            get {
                return ResourceManager.GetString("Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tríadas Mayores.
        /// </summary>
        internal static string MajorTriad {
            get {
                return ResourceManager.GetString("MajorTriad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Melódica menor.
        /// </summary>
        internal static string MelodicMinor {
            get {
                return ResourceManager.GetString("MelodicMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tríadas Menores.
        /// </summary>
        internal static string MinorTriad {
            get {
                return ResourceManager.GetString("MinorTriad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mixolidia.
        /// </summary>
        internal static string Mixolydian {
            get {
                return ResourceManager.GetString("Mixolydian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap move_task_down {
            get {
                object obj = ResourceManager.GetObject("move_task_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap move_task_up {
            get {
                object obj = ResourceManager.GetObject("move_task_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MSX.
        /// </summary>
        internal static string MSX {
            get {
                return ResourceManager.GetString("MSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivos WYZTracker .MUS (*.mus)|*.mus|Todos los Archivos (*.*)|*.*.
        /// </summary>
        internal static string MUSFilter {
            get {
                return ResourceManager.GetString("MUSFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menor natural (Eólica).
        /// </summary>
        internal static string NaturalMinor {
            get {
                return ResourceManager.GetString("NaturalMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo patrón.
        /// </summary>
        internal static string NewPattern {
            get {
                return ResourceManager.GetString("NewPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canción nueva.
        /// </summary>
        internal static string NewSong {
            get {
                return ResourceManager.GetString("NewSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Octavas.
        /// </summary>
        internal static string NoScale {
            get {
                return ResourceManager.GetString("NoScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo instalar correctamente OpenAL. Por favor, instale manualmente OpenAL..
        /// </summary>
        internal static string OpenALInstallError {
            get {
                return ResourceManager.GetString("OpenALInstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la instalación de OpenAL.
        /// </summary>
        internal static string OpenALSetupError {
            get {
                return ResourceManager.GetString("OpenALSetupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir.
        /// </summary>
        internal static string OpenVerb {
            get {
                return ResourceManager.GetString("OpenVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] OX {
            get {
                object obj = ResourceManager.GetObject("OX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patrón {0}.
        /// </summary>
        internal static string PatternWithNumber {
            get {
                return ResourceManager.GetString("PatternWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pentatónica Mayor 1.
        /// </summary>
        internal static string PentatonicMajor1 {
            get {
                return ResourceManager.GetString("PentatonicMajor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pentatónica Mayor 2.
        /// </summary>
        internal static string PentatonicMajor2 {
            get {
                return ResourceManager.GetString("PentatonicMajor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pentatónica Menor.
        /// </summary>
        internal static string PentatonicMinor {
            get {
                return ResourceManager.GetString("PentatonicMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frigia.
        /// </summary>
        internal static string Phrygian {
            get {
                return ResourceManager.GetString("Phrygian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piano.
        /// </summary>
        internal static string Piano {
            get {
                return ResourceManager.GetString("Piano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pl {
            get {
                object obj = ResourceManager.GetObject("pl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_end {
            get {
                object obj = ResourceManager.GetObject("player_end", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_play {
            get {
                object obj = ResourceManager.GetObject("player_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_stop {
            get {
                object obj = ResourceManager.GetObject("player_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap removePattern {
            get {
                object obj = ResourceManager.GetObject("removePattern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es necesario reiniciar la aplicación para cambiar el idioma actual. ¿Quiere guardar la canción actual? .
        /// </summary>
        internal static string RestartMessage {
            get {
                return ResourceManager.GetString("RestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ru {
            get {
                object obj = ResourceManager.GetObject("ru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap switchuser {
            get {
                object obj = ResourceManager.GetObject("switchuser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar un número de semitonos a transponer..
        /// </summary>
        internal static string TransposeError {
            get {
                return ResourceManager.GetString("TransposeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atención.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] WHITRABT {
            get {
                object obj = ResourceManager.GetObject("WHITRABT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tonos completos.
        /// </summary>
        internal static string WholeTone {
            get {
                return ResourceManager.GetString("WholeTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WYZTracker song file..
        /// </summary>
        internal static string WYZFileDesc {
            get {
                return ResourceManager.GetString("WYZFileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivos WYZTracker .WYZ (*.wyz)|*.wyz|Todos los Archivos (*.*)|*.*.
        /// </summary>
        internal static string WYZFilter {
            get {
                return ResourceManager.GetString("WYZFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WYZTracker2 - {0}.
        /// </summary>
        internal static string WYZTrackerTitle {
            get {
                return ResourceManager.GetString("WYZTrackerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No está listo todavía... :(.
        /// </summary>
        internal static string YetToCome {
            get {
                return ResourceManager.GetString("YetToCome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spectrum ZX.
        /// </summary>
        internal static string ZX {
            get {
                return ResourceManager.GetString("ZX", resourceCulture);
            }
        }
    }
}
