//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WYZTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WYZTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap About {
            get {
                object obj = ResourceManager.GetObject("About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accept {
            get {
                object obj = ResourceManager.GetObject("accept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addPattern {
            get {
                object obj = ResourceManager.GetObject("addPattern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alert {
            get {
                object obj = ResourceManager.GetObject("alert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error en la aplicación. Por favor, envíe el fichero [Mis Documentos]\WYZTracker.log a:
        ///augusto.ruiz@gmail.com.
        ///¡Gracias!.
        /// </summary>
        internal static string ApplicationError {
            get {
                return ResourceManager.GetString("ApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos WYZTracker .ARP (*.arp)|*.arp|Todos los Archivos (*.*)|*.*.
        /// </summary>
        internal static string ArpeggioFilter {
            get {
                return ResourceManager.GetString("ArpeggioFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tríadas Aumentadas.
        /// </summary>
        internal static string AugmentedTriad {
            get {
                return ResourceManager.GetString("AugmentedTriad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_cancel {
            get {
                object obj = ResourceManager.GetObject("button_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canal {0}.
        /// </summary>
        internal static string ChannelWithNumber {
            get {
                return ResourceManager.GetString("ChannelWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cromática.
        /// </summary>
        internal static string Chromatic {
            get {
                return ResourceManager.GetString("Chromatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clonePattern {
            get {
                object obj = ResourceManager.GetObject("clonePattern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amstrad CPC.
        /// </summary>
        internal static string CPC {
            get {
                return ResourceManager.GetString("CPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap de {
            get {
                object obj = ResourceManager.GetObject("de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tríadas Disminuidas.
        /// </summary>
        internal static string DiminishedTriad {
            get {
                return ResourceManager.GetString("DiminishedTriad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dórica.
        /// </summary>
        internal static string Dorian {
            get {
                return ResourceManager.GetString("Dorian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WYZTracker necesita OpenAL para funcionar correctamente. ¿Desea descargarlo ahora?.
        /// </summary>
        internal static string DownloadOpenAL {
            get {
                return ResourceManager.GetString("DownloadOpenAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_add {
            get {
                object obj = ResourceManager.GetObject("edit_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_remove {
            get {
                object obj = ResourceManager.GetObject("edit_remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap el {
            get {
                object obj = ResourceManager.GetObject("el", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap en {
            get {
                object obj = ResourceManager.GetObject("en", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_0000 {
            get {
                object obj = ResourceManager.GetObject("env_0000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_0100 {
            get {
                object obj = ResourceManager.GetObject("env_0100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_1000 {
            get {
                object obj = ResourceManager.GetObject("env_1000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_1001 {
            get {
                object obj = ResourceManager.GetObject("env_1001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_1010 {
            get {
                object obj = ResourceManager.GetObject("env_1010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_1011 {
            get {
                object obj = ResourceManager.GetObject("env_1011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_1100 {
            get {
                object obj = ResourceManager.GetObject("env_1100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_1101 {
            get {
                object obj = ResourceManager.GetObject("env_1101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_1110 {
            get {
                object obj = ResourceManager.GetObject("env_1110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_1111 {
            get {
                object obj = ResourceManager.GetObject("env_1111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_continue {
            get {
                object obj = ResourceManager.GetObject("env_continue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap env_none {
            get {
                object obj = ResourceManager.GetObject("env_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap es {
            get {
                object obj = ResourceManager.GetObject("es", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exportarWYZ {
            get {
                object obj = ResourceManager.GetObject("exportarWYZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos de audio .OGG (*.ogg)|*.ogg|Archivos de audio .WAV (*.wav)|*.wav|Todos los Archivos (*.*)|*.*.
        /// </summary>
        internal static string ExportFilter {
            get {
                return ResourceManager.GetString("ExportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filenew {
            get {
                object obj = ResourceManager.GetObject("filenew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileopen {
            get {
                object obj = ResourceManager.GetObject("fileopen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filesave {
            get {
                object obj = ResourceManager.GetObject("filesave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FX.
        /// </summary>
        internal static string FX {
            get {
                return ResourceManager.GetString("FX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos de instrumentos WYZTracker .FX (*.fx)|*.fx|Archivos WYZTracker .WYZ (*.wyz)|*.wyz|Todos los Archivos (*.*)|*.*.
        /// </summary>
        internal static string FXFilter {
            get {
                return ResourceManager.GetString("FXFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armónica menor.
        /// </summary>
        internal static string HarmonicMinor {
            get {
                return ResourceManager.GetString("HarmonicMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este identificador lo está usando el efecto &apos;{0}&apos;..
        /// </summary>
        internal static string IdAlreadyInUse {
            get {
                return ResourceManager.GetString("IdAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap importarMus {
            get {
                object obj = ResourceManager.GetObject("importarMus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos de instrumentos WYZTracker .INS (*.ins)|*.ins|Archivos WYZTracker .WYZ (*.wyz)|*.wyz|Todos los Archivos (*.*)|*.*.
        /// </summary>
        internal static string INSFilter {
            get {
                return ResourceManager.GetString("INSFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este identificador lo está usando el instrumento &apos;{0}&apos;..
        /// </summary>
        internal static string InstrIdAlreadyInUse {
            get {
                return ResourceManager.GetString("InstrIdAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keyboard {
            get {
                object obj = ResourceManager.GetObject("keyboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lidia.
        /// </summary>
        internal static string Lydian {
            get {
                return ResourceManager.GetString("Lydian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayor.
        /// </summary>
        internal static string Major {
            get {
                return ResourceManager.GetString("Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tríadas Mayores.
        /// </summary>
        internal static string MajorTriad {
            get {
                return ResourceManager.GetString("MajorTriad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melódica menor.
        /// </summary>
        internal static string MelodicMinor {
            get {
                return ResourceManager.GetString("MelodicMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tríadas Menores.
        /// </summary>
        internal static string MinorTriad {
            get {
                return ResourceManager.GetString("MinorTriad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixolidia.
        /// </summary>
        internal static string Mixolydian {
            get {
                return ResourceManager.GetString("Mixolydian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap move_task_down {
            get {
                object obj = ResourceManager.GetObject("move_task_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap move_task_up {
            get {
                object obj = ResourceManager.GetObject("move_task_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSX / Spectrum.
        /// </summary>
        internal static string MSX {
            get {
                return ResourceManager.GetString("MSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos WYZTracker .MUS (*.mus)|*.mus|Todos los Archivos (*.*)|*.*.
        /// </summary>
        internal static string MUSFilter {
            get {
                return ResourceManager.GetString("MUSFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menor natural (Eólica).
        /// </summary>
        internal static string NaturalMinor {
            get {
                return ResourceManager.GetString("NaturalMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo patrón.
        /// </summary>
        internal static string NewPattern {
            get {
                return ResourceManager.GetString("NewPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canción nueva.
        /// </summary>
        internal static string NewSong {
            get {
                return ResourceManager.GetString("NewSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octavas.
        /// </summary>
        internal static string NoScale {
            get {
                return ResourceManager.GetString("NoScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la instalación de OpenAL.
        /// </summary>
        internal static string OpenALSetupError {
            get {
                return ResourceManager.GetString("OpenALSetupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        internal static string OpenVerb {
            get {
                return ResourceManager.GetString("OpenVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OX {
            get {
                object obj = ResourceManager.GetObject("OX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrón {0}.
        /// </summary>
        internal static string PatternWithNumber {
            get {
                return ResourceManager.GetString("PatternWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentatónica Mayor 1.
        /// </summary>
        internal static string PentatonicMajor1 {
            get {
                return ResourceManager.GetString("PentatonicMajor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentatónica Mayor 2.
        /// </summary>
        internal static string PentatonicMajor2 {
            get {
                return ResourceManager.GetString("PentatonicMajor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentatónica Menor.
        /// </summary>
        internal static string PentatonicMinor {
            get {
                return ResourceManager.GetString("PentatonicMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frigia.
        /// </summary>
        internal static string Phrygian {
            get {
                return ResourceManager.GetString("Phrygian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piano.
        /// </summary>
        internal static string Piano {
            get {
                return ResourceManager.GetString("Piano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pl {
            get {
                object obj = ResourceManager.GetObject("pl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_end {
            get {
                object obj = ResourceManager.GetObject("player_end", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_play {
            get {
                object obj = ResourceManager.GetObject("player_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_stop {
            get {
                object obj = ResourceManager.GetObject("player_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap removePattern {
            get {
                object obj = ResourceManager.GetObject("removePattern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es necesario reiniciar la aplicación para cambiar el idioma actual. ¿Quiere guardar la canción actual? .
        /// </summary>
        internal static string RestartMessage {
            get {
                return ResourceManager.GetString("RestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ru {
            get {
                object obj = ResourceManager.GetObject("ru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap switchuser {
            get {
                object obj = ResourceManager.GetObject("switchuser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe indicar un número de semitonos a transponer..
        /// </summary>
        internal static string TransposeError {
            get {
                return ResourceManager.GetString("TransposeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WHITRABT {
            get {
                object obj = ResourceManager.GetObject("WHITRABT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonos completos.
        /// </summary>
        internal static string WholeTone {
            get {
                return ResourceManager.GetString("WholeTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WYZTracker song file..
        /// </summary>
        internal static string WYZFileDesc {
            get {
                return ResourceManager.GetString("WYZFileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos WYZTracker .WYZ (*.wyz)|*.wyz|Todos los Archivos (*.*)|*.*.
        /// </summary>
        internal static string WYZFilter {
            get {
                return ResourceManager.GetString("WYZFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WYZTracker2 - {0}.
        /// </summary>
        internal static string WYZTrackerTitle {
            get {
                return ResourceManager.GetString("WYZTrackerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No está listo todavía... :(.
        /// </summary>
        internal static string YetToCome {
            get {
                return ResourceManager.GetString("YetToCome", resourceCulture);
            }
        }
    }
}
