//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WYZTracker.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WYZTracker.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos de percusiones WYZTracker .FX (*.fx)|*.fx|Archivos WYZTracker .WYZ (*.wyz)|*.wyz|Todos los Archivos (*.*)|*.*.
        /// </summary>
        internal static string FXFilter {
            get {
                return ResourceManager.GetString("FXFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos de instrumentos WYZTracker .INS (*.ins)|*.ins|Archivos WYZTracker .WYZ (*.wyz)|*.wyz|Todos los Archivos (*.*)|*.*.
        /// </summary>
        internal static string INSFilter {
            get {
                return ResourceManager.GetString("INSFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piano.
        /// </summary>
        internal static string Piano {
            get {
                return ResourceManager.GetString("Piano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos de efectos WYZTracker .SFX (*.sfx)|*.sfx|Archivos WYZTracker .WYZ (*.wyz)|*.wyz|Todos los Archivos (*.*)|*.*.
        /// </summary>
        internal static string SfxFilter {
            get {
                return ResourceManager.GetString("SfxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos WYZTracker .WYZ (*.wyz)|*.wyz|Todos los Archivos (*.*)|*.*.
        /// </summary>
        internal static string WYZFilter {
            get {
                return ResourceManager.GetString("WYZFilter", resourceCulture);
            }
        }
    }
}
